### ISSUE TITLE
Can I use this inner a div?

### ISSUE THREAD

**Issue by dpy1123** [mark-rolich/RulersGuides.js#11]
Hi, there. I`m looking for a PhotoShop-like ruler frame, and I wanner how to use this inner a div.
Thx for you great job.

**Comment by ispringer** [comment]
+1. It would be great if you could optionally specify an arbitrary div to add the rulers to, e.g.:

```
var evt         = new Event(),
    dragdrop    = new Dragdrop(evt),
    rg          = new RulersGuides(evt, dragdrop, myDiv);
```

I am working on a WYSIWYG HTML editor, and I would like to add rulers to just the editor canvas portion of the page.

**Comment by mark-rolich** [comment]
Possible implementation is described in #16
