### ISSUE TITLE
How to add Grid line and rulers for particular div

### ISSUE THREAD

**Issue by 27viveks** [mark-rolich/RulersGuides.js#15]
Hi buddy,
           Here, I am struggle with to add rulers for particular inner div using this rulerguides.js.But i dont achieved it.Here i tried to add rulers for div like photoshop.
My current changed script:
<code>
var evt         = new Event(),

```
dragdrop    = new Dragdrop(evt),

rg          = new RulersGuides(evt, dragdrop, document.getElementById('workarea'));
```

</code>
I get this code for this issues :https://github.com/mark-rolich/RulersGuides.js/issues/11
How to changed ruler for div.

**Comment by mark-rolich** [comment]
Possible implementation is described in #16
