### ISSUE TITLE
Snap rules to DOM elements

### ISSUE THREAD

**Issue by victorb** [mark-rolich/RulersGuides.js#3]
Hey! Great stuff, love the bookmark functionality!

One thing that would be even better would be a mode where the rules snap to DOM elements.

Suggestion comes from here: https://news.ycombinator.com/item?id=6449883

**Comment by mark-rolich** [comment]
Thank you!
That would be really useful, I will work on that.

**Comment by FundCoders** [comment]
Looking forward to this enhancement? Bid some money, get a quicker implementation and reward the coders on
[FundCoders.com](http://www.fundcoders.com/Bid#/mark-rolich/RulersGuides.js/issues/3)

**Comment by adavenue** [comment]
How do you install it, so you can view live web pages?

**Comment by mark-rolich** [comment]
Bookmark the link on demo page or drag it to bookmarks bar
(http://en.wikipedia.org/wiki/Bookmarklet#Installation)

**Comment by mark-rolich** [comment]
I've implemented snap to DOM functionality.
Currently marked as experimental, needs testing.
