### ISSUE TITLE
Make ruler fixed to top/left on scroll

### ISSUE THREAD

**Issue by TheSharpieOne** [mark-rolich/RulersGuides.js#4]
When scrolling vertically up/down the page.  The top x-axis ruler should always be visible.  Similarly, when scrolling horizontally left/right the page.  The left y-axis ruler should also be visible.

Also, note that when scrolling, the ruler should still show the offset from the top left, (0,0).  Using position: fixed will keep them on screen, but not display the correct offsets.

**Comment by victorb** [comment]
This would be perfect as an option. In some cases, you want to be able to scroll with exactly the same rulers and sometimes you want to be able to make other rules after the fold.

**Comment by mark-rolich** [comment]
Added as an option, Ctrl+Alt+L will toggle rulers lock/unlock
