### ISSUE TITLE
Update ruler length on page re-size

### ISSUE THREAD

**Issue by TheSharpieOne** [mark-rolich/RulersGuides.js#5]
With dynamic content, the page's height and/or width may change.  The ruler may be too large or too small for the page based on the changing content.  toggling the ruler does not seem to resolve this issue.  It would be best if the ruler would update its size on the page's re-size event.

Examples after re-sizing this page:
![image](https://f.cloud.github.com/assets/664714/1218815/5738b9ae-26c0-11e3-8981-044b60fc1b65.png)
The ruler does not extend far enough

![image](https://f.cloud.github.com/assets/664714/1218818/67fb18a4-26c0-11e3-8162-ab068e3b05ce.png)
The ruler extends too far and makes the page wider.

**Comment by mark-rolich** [comment]
Issue fixed
