### ISSUE TITLE
Make content zoomable, or add magnifier window

### ISSUE THREAD

**Issue by davidzoli** [mark-rolich/RulersGuides.js#6]
It's a great tool! But I want to put pixel ferfect guides. It's not easy to do now.
Can you add some options to zoom the content? Or some little window magnifying the mouse area?

If I want to make sure about positions or dimensions, nowdays I have to make a screenshot, paste it into PS, zoom in and use guides. With this I could forget that method.

**Comment by mark-rolich** [comment]
Thank you!

You can zoom the web page itself, rulers and guides will zoom automatically.
It works on zoom values multiple of 100%, as all dimensions are calculated in pixels.

**Comment by davidzoli** [comment]
Oh yes, you're right!
I tested it in the demo site. The clue is "multiple of 100%" :)

It works!
Thanks
