### ISSUE TITLE
Fix toggle

### ISSUE THREAD

**Issue by KittyGiraudel** [mark-rolich/RulersGuides.js#7]
When toggling the bookmarklet on and off, it basically changes the display of both `.ruler` elements from `none` to `block` and vice versa. Any chance you could change the display value of their parent (`.rg-overlay`) instead? 

Currently, it makes the site unsable as soon as you have enabled the bookmarklet once, even if you have used it again in order to turn it off. This because the full screen overlay remains and prevents the site below from being used.

Using `pointer-events: none` could be a solution if you have some solid reasons not to move the show/hide to the parent.

Thanks!

**Comment by mark-rolich** [comment]
Thanks for pointing out that.
Overlay is toggled on "Toggle rulers and guides" and on bookmarklet click.
