### ISSUE TITLE
Chrome Plugin?

### ISSUE THREAD

**Issue by wiedikerli** [mark-rolich/RulersGuides.js#8]
This plugin looks awesome. It would be greate if there is a plugin for Chrome

**Comment by aziz** [comment]
:+1: for turning this to a browser extension

**Comment by mark-rolich** [comment]
Done, extension is located at http://mark-rolich.github.io/RulersGuides.js/RulersGuides.crx
You need to download it and install manually (drag and drop the downloaded file to extensions tab, chrome://extensions)

**Comment by jr0131** [comment]
Awesome.  Thank you sooooo much!

## 

Judy Rose

JRose Designs

 http://jrosedesigns.com/ http://jrosedesigns.com
Phone: 509-534-1221
jrose@jrosedesigns.com

Our prereference, for hosting & domain name transactions ,is:

 http://secure.hostgator.com/cgi-bin/affiliates/clickthru.cgi?id=judyrose Hostgator - Safe, Secure, 24/7 Hosting

**Comment by wiedikerli** [comment]
Awesome!!!!!
