### ISSUE TITLE
Using the "Show detailed info" feature

### ISSUE THREAD

**Issue by harwooje** [mark-rolich/RulersGuides.js#9]
Our site  has been migrated to Wordpress.  RulersGuides.js would be great for layout, except the horizontal ruler across the top of the page is almost covered by the WordPress admin toolbar.  So, the little red menu icon for the rulers (top/ left) is covered and unusable.

I could use the hot keys associated with the menu items but when I invoke "Cntrl Alt I" for the detailed information I get this Javascript error:

"TypeError: 'null' is not an object (evaluating 'vRuler.style')" 

Here a screenshot of how the menu lays out in WordPress -- showing the errors (ignore the first two errors):

![snap_02](https://f.cloud.github.com/assets/2712039/1290223/3a8f3834-302d-11e3-9358-1b625f30ec02.jpg)

If I could get the hot key combination to work the problem would be solved.

Thanks,

JH

**Comment by mark-rolich** [comment]
Do you use the latest version ?
I've tried to reproduce that on the wordpress admin demo, it works without issues

**Comment by harwooje** [comment]
I guess that's it ( I replaced the bookmark with the "rulers-guides-2013-10-08" version and it works.

Thanks,

JH

On Oct 9, 2013, at 1:30(23) AM, Mark Rolich <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you use the latest version ?
I've tried to reproduce that on the wordpress admin demo, it works without issues
